
Através do dataset dados.csv será executado um processo de análise de dados exploratória para conhecimento/entendimento destes dados.


```{r}
#paleta de cores
library("RColorBrewer")
```



```{r}
dados = read.csv("dados.csv", sep=';')
dados
```

RESUMO ESTATÍSTICO - dados numéricos
```{r}
summary(dados[3:4])
```


ALGUNS GRÁFICOS


VALOREMPENHO - boxplot
```{r}
boxplot(dados$VALOREMPENHO, main='Valores de Empenho', col = brewer.pal(n = 3, name = "Pastel1"))
```

VALOREMPENHO - histograma
```{r}
hist(dados$VALOREMPENHO, main='Valores de Empenho', ylab='Frequência', xlab='Empenho', col=brewer.pal(n=3, name='Paired') )
```



PIB - boxplot
```{r}
boxplot(dados$PIB, main='PIB', col = brewer.pal(n = 5, name='Paired'))
```


PIB - histograma
```{r}
hist(dados$PIB, main='PIB', ylab='Frequência', xlab=NULL, col=brewer.pal(n=3, name='Pastel2'))
```


Busca os maiores empenhos
```{r}
Mempenho = head(dados[order(-dados$VALOREMPENHO),], 10)
barplot(Mempenho$VALOREMPENHO, col=brewer.pal(n=10, name='RdBu'), las=2, main='Maiores Empenhos')
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "RdBu"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```


Maiores PIBs
```{r}
Mpibs = head(dados[order(-dados$PIB),], 10)
barplot(Mpibs$PIB, col=brewer.pal(n=10, name='Spectral'), las=2, main='Maiores PIBs')
legend('topright', legend=Mempenho$MUNICIPIO, col=brewer.pal(n=10, name='Spectral'), lty=1:2, cex=0.8, ncol=2, lwd=4 )
box()

```


Relação entre PIB e EMPENHO

```{r}
#Calcula qual % de PIB foi empenhado
dados$PROPORCAO = dados$VALOREMPENHO / dados$PIB
Mprop = head(dados[order(-dados$PROPORCAO), ], 10)
barplot(Mprop$PROPORCAO,col=brewer.pal(n = 10, name = "Set2"),las=2,main = "Maiores Gastos em Proporção ao PIB")
legend("topright",legend=Mprop$MUNICIPIO,col = brewer.pal(n = 10, name = "Set2"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()

```


















